name: golangci-lint
on:
  pull_request:
    branches: [ NewArc ]
    paths:
      - '**/*.go'
      - '.golangci.yml'
      - '.golangci.yaml'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    env:
      GONOSUMDB: github.com/xorewa/*
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
          cache: false
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.64.5

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0 --print-issued-lines

          # Report only issues introduced by the NewArc pull request.
          only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go
          # skip-go-installation: true
