name: Tests

on:
  push:
    branches: [ NewArc ]
  pull_request:
    branches: [ NewArc ]

permissions:
  contents: read

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    env:
      GONOSUMDB: github.com/xorewa/*
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Check out code
        uses: actions/checkout@v4
      - name: Unit tests
        run: |
          go test ./...
