name: Run multiple simulators

on:
  push:
    branches: [ NewArc ]
  pull_request:
    branches: [ NewArc ]

permissions:
  contents: read

jobs:
  build:
    name: Run instances
    runs-on: ubuntu-latest
    env:
      GONOSUMDB: github.com/xorewa/*
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download
      - name: Run multiple instances
        run: |
          cd cmd/chainsimulator 
          go build
          ./chainsimulator --fetch-configs-and-close
          python3 ../../scripts/run-multiple-instances/script.py
