name: Run VM query
on:
  push:
    branches: [ NewArc ]
  pull_request:
    branches: [ NewArc ]

permissions:
  contents: read

jobs:
  build:
    name: Run chain simulator and VM query
    runs-on: ubuntu-latest
    env:
      GONOSUMDB: github.com/xorewa/*
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download
      - name: Run VM query after start
        run: |
          cd cmd/chainsimulator 
          go build
          ./chainsimulator --fetch-configs-and-close
          screen -dmS chainsimulator "./chainsimulator"
          ./../../scripts/run-vm-query/script.sh
